on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello Reactor Demo
        uses: vivsridh4/hello-world-reactor-demo@v2
        with:
          who-to-greet: 'Welcome to Reactor #AzureHappyHours'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
